remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Project 6
description: Through this project we worked with class inheritence. We also gained experience debugging code and practiced using modern JavaScript syntax. Used a generic block of code to process data
